"""Renombrar password a password_hash

Revision ID: bf9f6328779a
Revises: ec30ee75a83f
Create Date: 2025-07-03 02:22:50.024988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf9f6328779a'
down_revision = 'ec30ee75a83f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=256), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
